### ISSUE TITLE
Výchozí konstrukce peristaltické pumpy

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/PERISTALTIC01#1]
Na [Thingiverse](https://www.thingiverse.com/search?q=peristaltic+nema&type=things&sort=relevant) je třeba najít nějaký rozumně kvalitní scad zdroják na peristaltickou pumpu pro motor formátu [NEMA17](https://en.wikipedia.org/wiki/NEMA_stepper_motor).

Nalezený zdroják je potřeba prověřit a nahrát do tohoto repozitáře.

**Comment by JanKott** [comment]
Prošel jsem na thingiverse peristaltické pumpy a našel následující:

Nejlepší kandidát bych řekl že je toto
https://www.thingiverse.com/thing:3148717/files
Používá NEMA motor a 6 ložisek 605zz.
Je tam i poměrně dlouhé video kde prezentuje výsledek.

Další varianty jsou tyto:

https://www.thingiverse.com/thing:3591068
Původně navrhováno pro hydroponii, nikdy nedotaženo. Bez použití ložisek.

https://www.thingiverse.com/thing:2378810/files
Používá HS-755MG servo a 6 625 kuličkových ložisek. Dokončený vývoj (funkční).

https://www.thingiverse.com/thing:2856784/files
Tohle je asi jen mount pro NEMA17? Zdá se že tam neni rotační část pro upevnéní ložisek. Musel bych projít ten .scad

https://www.thingiverse.com/thing:1572181
Varianta bez ložisek. Zdá se že tuhle variantu většina motorů neutáhne.

https://www.thingiverse.com/thing:8964
Opět plně plastová varianta, nedokončená.

https://www.thingiverse.com/thing:454702
Planetární převodovka upravená jako peristaltická pumpa.

https://www.thingiverse.com/thing:2619479
Zdrojové soubory v Inventoru.

**Comment by kaklik** [comment]
> Nejlepší kandidát bych řekl že je toto
> https://www.thingiverse.com/thing:3148717/files
> Používá NEMA motor a 6 ložisek 605zz.
> Je tam i poměrně dlouhé video kde prezentuje výsledek.
>

Souhlasím

 
> https://www.thingiverse.com/thing:2856784/files
> Tohle je asi jen mount pro NEMA17? Zdá se že tam neni rotační část pro upevnéní ložisek. Musel bych projít ten .scad

Tohle je myslím trochu horší varianta, neboť neřeší možnost dilatace přesností mezi rotorem a statorem.


> 
> https://www.thingiverse.com/thing:1572181
> Varianta bez ložisek. Zdá se že tuhle variantu většina motorů neutáhne.
> 
> https://www.thingiverse.com/thing:8964
> Opět plně plastová varianta, nedokončená.
> 
> https://www.thingiverse.com/thing:454702
> Planetární převodovka upravená jako peristaltická pumpa.

Tyhle různé alternativy planetových převodovek provozované  jako peristaltické pumpy by byly pěkné. Ale  bylo by nutné nějak zajistit, aby rotor měl vůči statoru nějakou možnost dilatování nepřesností.  Možná by to šlo zařídit snížením tuhosti vnějšího kroužku statoru, ale je to úkol pro samostatný vývoj.

**Comment by JanKott** [comment]
Převzal jsem tedy soubory z vybraného projektu na thingiverse. Soubory jsem uložil podle připravené struktury souborů a dogeneroval jsem AMF a GCODE soubory pro tisknutelné části.
Do Makefile jsem doplnil volání make print, které generuje pouze AMF a GCODE pro tisknutelné části.

**Comment by JanKott** [comment]
Doplnim do projektu nástroje amfsort a merge_slic3r_conf a přidám github actions na make po každém push.

**Comment by kaklik** [comment]
Github actions je funkční.
