### ISSUE TITLE
Úprava uchyceni peristaltické pumpy

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/PERISTALTIC01#2]
Nalezenou konstrukci z issue #1  je potřeba upravit tak, aby bylo možné celé čerpadlo uchytit na [základní desku MLAB](https://github.com/MLAB-project/Modules/blob/master/mechanical/ALBASE1521/doc/ALBASE1521.cs.pdf).

Je potřeba uvažovat že pump může vedle sebe být více a je tak potřeba šetřit místem. 
Na stejnou desku by se zároveň měla vejít i elektronika, která se bude primárně skládat z modulu [HBSTEP01B](https://www.mlab.cz/module/HBSTEP01B) a nějakého vhodného rozhraní pro jeho ovládání.  Například kombinace modulů [I2CSPI](https://www.mlab.cz/module/I2CSPI01A) a [USBI2C](https://www.mlab.cz/module/USBI2C01A). Tyto dva poslední moduly mohou obsluhovat jeden až čtyři moduly HBSTEP01B.

**Comment by JanKott** [comment]
Aktualizoval jsem modul stator_base tak, aby šlo čerpadlo uchytit na základní desku MLAB ALBASE1521.
Doplnil jsem do složky assembly soubor pump_mount.scad kde je naznačena jedna z možností jak uchytit 4 pumpy. Nevím ovšem, jestli se doprostřed vejdou menší moduly mezi NEMA motory jak je naznačeno, protože nevím jaký je jejich přesah.
