### ISSUE TITLE
Úprava konstrukce pro dostupnější ložiska 625Z

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/PERISTALTIC01#4]
Současná konstrukce je navržena pro ložiska 605Z, které má menší vnější průměr. Ložiska 625Z s v nějším průměrem 16 mm se tak do rotoru pumpy nevejde.

![20210116_224946](https://user-images.githubusercontent.com/1194177/105178827-d37df980-5b28-11eb-9ea6-a9d50f4260d8.jpeg)

Řešením je zjistit, zda lze v modelu změnit parametry ložiska tak, aby ostatní díly modelu byly přepočítány způsobem, který zachová funkčnost.

**Comment by JanKott** [comment]
Upraveno a přegenerováno.

**Comment by kaklik** [comment]
Do upraveného dílu ložiska pasují. :)
